### ISSUE TITLE
Invalid call to Revit API! Revit is currently not within an API context.

### ISSUE THREAD

**Issue by ttiefenbach** [jeremytammik/ModifyTabButton#1]
When I try to use your sample code, I get this error in the journal file: "Invalid call to Revit API! Revit is currently not within an API context."  It occurs in the "OnUiElementActivated" function at the line:
```
_controlledApp.Idling += new EventHandler<IdlingEventArgs>( OnButtonIdling );
```
I'm testing in Revit 2016.

**Comment by jeremytammik** [comment]
The error message is probably absolutely correct, and the architecture of this app flawed. It could probably be solved as follows: on startup, implement and connect an external event. in `OnUiElementActivated `, raise the external event. Revit became stricter on enforcing the valid API context as time went by, and that is good, and uncovered this flaw. Capisci? Ciao!
